# Generated by Django 3.1.2 on 2020-10-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201017_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='is_one_time',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
